### ISSUE TITLE
部署完之后1003error

### ISSUE THREAD

**Issue by liu-dejin** [nICEnnnnnnnLee/GithubSoEasy#2]
Error 1003 Ray ID: 8593e8a3f3090462 • 2024-02-22 02:48:12 UTC
Direct IP access not allowed

**Comment by nICEnnnnnnnLee** [comment]
自定义的域名没有配置，或者配置错误就是这样的。  

在实际操作里，你自定义的域名是怎么配置的？你访问的url又是什么？

https://github.com/nICEnnnnnnnLee/GithubSoEasy/blob/af1c545c427c80f6f99399a7185ba95d21e7847d/index.js#L2

**Comment by liu-dejin** [comment]
已经成功配置,蟹蟹٩('ω')و
