### ISSUE TITLE
when i browsed my web via xiaomi browser,i got this exception

"exceptions": [

{

"stack": " at fetchAndStream (worker.js:60:60)",

"name": "TypeError",

"message": "Cannot read properties of null (reading 'toLowerCase')",

"timestamp": 1711936056099

}

],

it is ok by Chrome.sob...

### ISSUE THREAD

**Issue by lutcraft** [nICEnnnnnnnLee/GithubSoEasy#4]
"exceptions": [

{

"stack": " at fetchAndStream (worker.js:60:60)",

"name": "TypeError",

"message": "Cannot read properties of null (reading 'toLowerCase')",

"timestamp": 1711936056099

}

],

**Comment by nICEnnnnnnnLee** [comment]
你使用的`index.js`不是最新的。就可用性而言，需要在原来的基础上增加`?`

https://github.com/nICEnnnnnnnLee/GithubSoEasy/blob/9874c8bbee743adae78f2adec285a20c29671ad4/index.js#L63

**Comment by lutcraft** [comment]
> 你使用的`index.js`不是最新的。就可用性而言，需要在原来的基础上增加`?`
> 
> https://github.com/nICEnnnnnnnLee/GithubSoEasy/blob/9874c8bbee743adae78f2adec285a20c29671ad4/index.js#L63

it worked, thanks！
